export * from './components.module'
export * from './main/main-page/main-page.component'
export * from './main/main-page/owner-table/owner-table.component'
export * from './main/button-panel/button-panel.component'
export * from './redact/redact.component'
export * from './redact/redact-owner/redact-owner.component'
export * from './redact/redact-cars/redact-cars.component'
export * from './redact/redact-buttons/redact-buttons.component'
